### Update number of responders

PUT http://localhost:3001/api/farmerConfirm/57/2021/1


### Adding new transaction
POST http://localhost:3001/api/sendPickupReminder
Content-Type: application/json

{ }


### Adding new transaction
GET http://localhost:3001/api/orders/pickup/clientorder
