### Update number of responders

PUT http://localhost:3001/api/clients/update/balance/1/10


### Adding new transaction
POST http://localhost:3001/api/transactions
Content-Type: application/json

{ "type":"top-up", "client_id":1, "method_id":1, "account_num":"4217484694987474","amount":10, "date":"14-11-2021", "time":"15:44", "status":1 }