### Update number of responders

PUT http://localhost:3001/api/farmerConfirm/57/2021/1


### send telegram notification about updates
POST http://localhost:3001/api/SendTelegramNotification
Content-Type: application/json

{ }

### send telegram notification about insufficient balance
POST http://localhost:3001/api/SendTelegramNotificationForInsufficientBalance
Content-Type: application/json

{ }


### Adding new transaction
GET http://localhost:3001/api/clientsOrdersWithTelegram


### API for telegram

GET https://api.telegram.org/bot5048293827:AAGa6eTGLM24v30dNJFVdjZljR8EYS-xNHA/getUpdates


### get webhooks

GET https://api.telegram.org/bot5048293827:AAGa6eTGLM24v30dNJFVdjZljR8EYS-xNHA/getWebhookInfo


### Adding new transaction
POST https://api.telegram.org/bot5048293827:AAGa6eTGLM24v30dNJFVdjZljR8EYS-xNHA/sendMessage
Content-Type: application/json

{ "chat_id": "-787241646", "text":"Hello from the bot" }



### Adding new transaction
POST http://localhost:3001/api/topUpNotificationTelegram
Content-Type: application/json

{ "balance": "150", "telegramId":"836952271" }

